# Generated by Django 4.1.3 on 2022-11-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='carrera_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Carrera id'),
        ),
    ]
