# Generated by Django 4.1.3 on 2022-11-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0003_encargado_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['rut', 'nombre', 'apellidos', 'correo', 'contraseña'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='contraseña',
            field=models.CharField(default=0, max_length=100, verbose_name='Contraseña'),
        ),
    ]
