# Generated by Django 4.1.3 on 2022-11-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0004_alter_alumno_options_alumno_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='contraseña',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Contraseña'),
        ),
    ]
