# Generated by Django 4.1.3 on 2022-12-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0005_alter_alumno_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=3, verbose_name='Estado Solicitud')),
                ('fecha_solicitud', models.DateTimeField(verbose_name='Fecha de Solicitud')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnado.alumno')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
            },
        ),
    ]
