# Generated by Django 4.1.3 on 2022-12-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0006_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='deporte',
            field=models.CharField(default=0, max_length=20, verbose_name='Deporte'),
        ),
    ]
