# Generated by Django 4.1.3 on 2022-12-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0007_solicitud_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='pen', max_length=3, verbose_name='Estado Solicitud'),
        ),
    ]
