# Generated by Django 4.1.3 on 2022-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0008_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuario.png', max_length=255, null=True, upload_to='imagen', verbose_name='imagen'),
        ),
    ]
