# Generated by Django 4.1.1 on 2022-12-15 21:49

import Alumnado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0011_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuarios/usuario.png', null=True, upload_to=Alumnado.models.Usuario.generaNombre, verbose_name='Imagen'),
        ),
    ]
