# Generated by Django 4.1.1 on 2022-12-15 22:40

import Alumnado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0012_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(default='alumnos/alumno.png', null=True, upload_to=Alumnado.models.Alumno.generaNombre, verbose_name='Imagen'),
        ),
    ]
