# Generated by Django 4.1.1 on 2022-12-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0013_alumno_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='deporte',
            field=models.CharField(default='futbol', max_length=20, verbose_name='Deporte'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='pendiente', max_length=100, verbose_name='Estado Solicitud'),
        ),
    ]
