# Generated by Django 4.1.3 on 2022-12-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnado', '0014_alter_solicitud_deporte_alter_solicitud_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosCovid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.CharField(default='sin síntomas', max_length=100, verbose_name='Sintomas')),
                ('contactoEstrecho', models.CharField(default='no', max_length=2, verbose_name='Contacto estrecho')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnado.alumno')),
            ],
        ),
    ]
